### ISSUE TITLE
opt-out iframe n'est plus accessible

### ISSUE THREAD

**Issue by bamthomas** [iroco-co/landing#42]
depuis la mise en conformité avec la charte des chatons, l'iframe matomo n'est plus affichée.

**Comment by marc-bouvier** [comment]
Refused to frame 'https://matomo.iroco.co/' because it violates the following Content Security Policy directive: "frame-src 'self' https://xq520.mjt.lu".

![image](https://github.com/iroco-co/landing/assets/15436007/8c652219-90e8-49ad-9f6b-d5ae3e236664)

**Comment by marc-bouvier** [comment]
mjt.lu : mailjet

![image](https://github.com/iroco-co/landing/assets/15436007/183c456b-dbe1-40be-8ad1-c15d59352411)

**Comment by marc-bouvier** [comment]
[Is the Matomo JavaScript Tracker CSP (Content Security Policy) compatible and how do I set it up?](https://matomo.org/faq/general/faq_20904/)
